### ISSUE TITLE
Fullscreen in IE10 error

### ISSUE THREAD

**Issue by tomul** [eXon/videojs-youtube#194]
Trying to enter fullscreen in IE10 (Win 7) throws an error: Object doesn't support property or method 'Ea' (with videojs controls) . Works fine in IE11, Chrome and Firefox. 

Thanks

**Comment by sanketj14** [comment]
Hi,

This issue seems to be still there, I am facing this issue on IE 9 & IE 10, even with unminified version, since https://github.com/videojs/videojs-youtube/commit/9d4119937d03804a8cea8cd788925e60a9443318  this commit is not present in the master version of the JS. it's throwing error as `object or property doesn't support method 'fullscreen'`, because `supportsfullscreen()` is always returning true from `video-youtube.js`. I'm not sure why this code is not in master version but please add this commit into the next release, as this issue is still open.

Thanks.
