### ISSUE TITLE
How can we add overlays for youtube videos in iframe or in video tag dynamically

### ISSUE THREAD

**Issue by sujivasagam** [eXon/videojs-youtube#242]
I wish to add the overlays dynamically for the youtube videos in iframe or in video tag. I can't get the overlay details by using the video tag since the youtube.js converted the video tag into iframe before i got the src value of the video tag.

**Comment by eXon** [comment]
You can read more about skining your video player on the [video.js documentation](https://github.com/videojs/video.js/blob/stable/docs/guides/skins.md).

You shouldn't touch anything inside the iframe or the video element because it will screw things. If you need something additional, you can [make a plugin](https://github.com/videojs/video.js/blob/stable/docs/guides/plugins.md).
