### ISSUE TITLE
Fullscreen Video in IOS browsers

### ISSUE THREAD

**Issue by greglindquist** [eXon/videojs-youtube#98]
Hi, 

We're experiencing an issue with this plugin with IOS based devices (ios 6 or 7). We can play videos, but can't seem to view them fullscreen. We can view locally sourced video that are not using this plugin in fullscreen, and feel the issue is related to the Youtube plugin. Does anyone have any ideas?

Thanks!

**Comment by pirahana** [comment]
Hi,
  I am using video.js 5.9.1 and using latest youtube.js .It is not playing on ipad.It does play on chrome and firefox..Is there any techOrder for ipad

**Comment by narration-sd** [comment]
Hmm. I have it youtube running on iPad with 5.9.0. But I can probably suggest why you and everyone else is having trouble, having recently gone down a path with VideoJs and JWPlayer.

- Apple's iOS and its embedded browser, which all iPhone/iPads must use as their basis, has a very strange setup for video. They deliberately won't let it play without the user having directly touched the screen first, and when it does, they don't obey any normal rules for how css and layering are supposed to work.. The first part is to 'save' from autorun videos running up cellphone charges. The second is anyone's guess, but they do it.

- Then, Youtube changed to its iframe-onlly player, and the combination of this with Apple's peculiarity is pretty devastating. I don't think the videojs  youtube tech has worked well since that point, and if you dig in,, you'll find that any number of calls the frameworks suggests just plain don't exist, if they did before.

- eXon, who contributed the youtube tech, has begged off many months ago, with no effort forthcoming from the main videojs project. Before he had to leave, he tried to fix the iPad problem enough so it would basically work, even though he lacked test players. Very nice by him, not so great by the videojs project. 

- Now, I think if you will try the present youtube tech with _no_ plugins and _no_ poster, it will work on iPads and iPhones. At least it does so on my relatively ancient iPad 2, running latest iOS 9.3..1 and several releases before that, which actually really tax the machine.

- for my use, I need posters and I need a workable  offset start and stop, to piece out youtube videos created for other purposes. I think I've got a solution for the latest forked version of the offset plugin, as without this you are lost - both versions will fault out by stack faults in JavaScript. Posters, though, not - you'll just get a non-playing startup whirler forever with no play.

- I thought I would go to JWPlayer, as I discovered it had a decent API if that is somewhat hidden away. But in fact it does not seem to be able to properly handle start/stop offset on the Apple machines, with the usual sort of merrygoround of things that should work but don't, and interfere with each other or misbehave in part of the operation states.

- JWPlayer does apparentlyl handle posters correctly in the Apple environment as well as tamer places, as far as I've seen, so I think it can be done. However, with the event problems there, and also with their requirement that you run an informer to them for every video page load, I'm not thinking they're an attractive solution.

- A way forward would be to import the JW poster-iOS-taphandling method into videojs, as i suspect the number of ways this can actually work may be about the one. This with the rejigging of offsets would enable my intents. I just haven't found the time available to do this, or especially to publish with all the daunting requirements the videojs hobby project puts on any who think to contribute to it.

- my feeling is that each of these players who 'seem' to offer a free way to use them actually are mainly stalking horses for the proprietary video servers/services they wan to sell you. The players do itt seems all work fine with non-youtube mp4s, unless I have missed something in all the scrambling done. Fine enough for projects that have the money; not so fine  for the human community things at small scales which do not, no matter how much they might benefit from video.

- So. I haven't known what to do about this. I think laying the big responsibility on one person's shoulders isn't fair or workable -- even after the very nice and appreciated effort done by eXon, which may prove the point as he says he can't keep it up either. 

- I am trying to imagine that some cooperative combination of work could fix things. I'm too experienced not to wonder how the coordination would work. People _could_ work together, each taking a part. It wouldn't evidently have any help from the videojs angle, by the evidence.

- I think the most i could personally contribute besides the pointers here would be a set of code for upgrading the videojs-time-offset plugin -- this is the later forked version, more recently worked on. Soeone else would have to do the assuring of packaging it like the videojs project wants it, and especially meeting their testing armature requirements.

Thus, being that busy elsewhere, putting this out there...regards to each...

**Comment by narration-sd** [comment]
Oh yes, full-screen is another issue of many unusual facets on Apple i-devices. It's not supposed to work, I think, but on the other hand, at least some i-devices automatically go to full  screen. As well, on iPad with recent iOS, anyway, you can always  finger-stretch the video to (and beyond) full screen. 

Yes, it's a problem... I haven't dug far into this one, due to the others. All the iOS issues can be found discussed on the web, particularly via stackexchange(s).
